%YAML:1.0

#--------------------------------------------------------------------------------------------
# Input parameters
#--------------------------------------------------------------------------------------------

# Input path and file names
# Note: If you comment the lines, the corresponding images will not be output
Input.folder: "/Path/To/Input/Folder"

Input.video_1: "front.avi"
Input.video_2: "rear.avi"
Input.video_3: "left.avi"
Input.video_4: "right.avi"
Input.video_5: "frontcopy.avi"
Input.video_6: "leftcopy.avi"
Input.video_7: "rearcopy.avi"
Input.video_8: "rightcopy.avi"

Input.video_num: 6

Input.timestamps: "video_frame_info"


#--------------------------------------------------------------------------------------------
# Output parameters
#--------------------------------------------------------------------------------------------

# Output directories
# Note: If you comment the lines, the corresponding images will not be output
Output.folder:  "/Path/To/Output/Folder"

#--------------------------------------------------------------------------------------------
# Fisheye camera parameters
#--------------------------------------------------------------------------------------------

Fisheye.pixel_size: 0.003  # unit: mm
Fisheye.distortion_file:  "/Path/To/distort_table.txt"

Fisheye.fx: 3.3194312219513085e+02
Fisheye.fy: 3.3247184714548160e+02
Fisheye.cx: 6.3544175190834528e+02
Fisheye.cy: 3.5407725558319731e+02
Fisheye.width:            1280
Fisheye.height:           720


Fisheye.k1: 6.6089562556246650e-02
Fisheye.k2: 2.6735660842530651e-02
Fisheye.k3: -1.3559849664351880e-02
Fisheye.k4: 1.5734344135267359e-03
#--------------------------------------------------------------------------------------------
# Pinhole camera parameters
#--------------------------------------------------------------------------------------------

Pinhole.fx:       220.6
Pinhole.fy:       220.6
Pinhole.cx:       320.0
Pinhole.cy:       350.0
Pinhole.width:    640
Pinhole.height:   480
